namespace Jint.Parser.Ast
{
	public enum SyntaxNodes
	{
		AssignmentExpression = 0,
		ArrayExpression = 1,
		BlockStatement = 2,
		BinaryExpression = 3,
		BreakStatement = 4,
		CallExpression = 5,
		CatchClause = 6,
		ConditionalExpression = 7,
		ContinueStatement = 8,
		DoWhileStatement = 9,
		DebuggerStatement = 10,
		EmptyStatement = 11,
		ExpressionStatement = 12,
		ForStatement = 13,
		ForInStatement = 14,
		FunctionDeclaration = 15,
		FunctionExpression = 16,
		Identifier = 17,
		IfStatement = 18,
		Literal = 19,
		RegularExpressionLiteral = 20,
		LabeledStatement = 21,
		LogicalExpression = 22,
		MemberExpression = 23,
		NewExpression = 24,
		ObjectExpression = 25,
		Program = 26,
		Property = 27,
		ReturnStatement = 28,
		SequenceExpression = 29,
		SwitchStatement = 30,
		SwitchCase = 31,
		ThisExpression = 32,
		ThrowStatement = 33,
		TryStatement = 34,
		UnaryExpression = 35,
		UpdateExpression = 36,
		VariableDeclaration = 37,
		VariableDeclarator = 38,
		WhileStatement = 39,
		WithStatement = 40
	}
}
