namespace SF3.Moves
{
	public enum EIntervalsType
	{
		INTERVAL_NONE = 0,
		INTERVAL_ATTACK = 1,
		INTERVAL_NO_REPULSION = 2,
		INTERVAL_NO_WALL_REPULSION = 3,
		INTERVAL_DODGEABLE = 4,
		INTERVAL_BLOCKABLE = 5,
		INTERVAL_UNINTERRUPT = 6,
		INTERVAL_SELF_UNINTERRUPT = 7,
		INTERVAL_SLOWMOTION = 8,
		INTERVAL_INVINCIBLE = 9,
		INTERVAL_TRANSITIONAL = 10,
		INTERVAL_DISSOLVE_WEAPON = 11
	}
}
